name: check/updatewebbpsf cache

on:
  # TODO also cron
  workflow_dispatch:

jobs:
  webbpsf-data:
    name: fetch, check, and possibly update WEBBPSF data cache
    runs-on: ubuntu-latest
    env:
      DATA_PATH: /tmp/data
      WEBBPSF_DATA_URL: https://stsci.box.com/shared/static/qxpiaxsjwo15ml6m4pkhtk36c9jgj70k.gz
    outputs:
      path: ${{ steps.cache_path.outputs.path }}
      hash: ${{ steps.data_hash.outputs.hash }}
    steps:
      - id: cache_path
        run: |
          echo "path=${{ env.DATA_PATH }}" >> $GITHUB_OUTPUT
      - id: data_hash
        run: |
          mkdir -p tmp/data
          wget ${{ env.WEBBPSF_DATA_URL }} -O tmp/webbpsf-data.tar.gz
          echo "hash=$( shasum tmp/webbpsf-data.tar.gz | cut -d ' ' -f 1 )" >> $GITHUB_OUTPUT
      - id: cache_check
        uses: actions/cache@v3
        with:
          path: ${{ steps.cache_path.outputs.path }}
          key: webbpsf-${{ steps.data_hash.outputs.hash }}
      - if: ${{ steps.cache_check.outputs.cache-hit != 'true' }}
        name: Initialize cache
        run: |
          mkdir -p ${{ steps.cache_path.outputs.path }}
          tar -xzvf tmp/webbpsf-data.tar.gz -C ${{ steps.cache_path.outputs.path }}
